runtime: nodejs12
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
env_variables:
  NODE_ENV: "production"
  GOOGLE_APPLICATION_CREDENTIALS: "service-account-file.json"
